architecture: standalone

auth:
  enabled: true
  password: "dev-redis-password"

master:
  count: 1
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

replica:
  replicaCount: 0

metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # 若有 Prometheus 可打開
