replicaCount: 1

image:
  repository: <helm.set.image.repository>
  tag: <helm.set.image.tag>
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 2345
  annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: workerman.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - workerman.localhost
      secretName: workerman-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  appPvc: workerman-app-pvc
  size: 1Gi
  zshHistoryHostPath: /mnt/host-zsh-history/root.zsh_history
  storageClassName: ""
